module: Chord_Provider
title: Chord Provider
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/Chord-Provider/
build_tool_arguments:
 - -scheme
 - Chord Provider (macOS)
min_acl: private
output: Documentation
clean: true
theme: apple

custom_categories:

  - name: SwiftUI
    children:
    - ChordProviderApp
    - ContentView
    - MainView
    - ToolbarView
    - HeaderView
    - SongView
    - ChordsView
    - AudioPlayerView
    - EditorView
    - FileBrowserView
    - ExportSongView
    - MarkupCommands

  - name: ChordPro
    children:
    - ChordPro
    - Song
    
  - name: Observable Items
    children:
    - SceneState
    - DocumentFocusedValueKey
    - SceneFocusedValueKey
    - FocusedValues
    - FileBrowser

  - name: File Documents
    children:
    - UTType
    - ChordProDocument
    - ExportDocument
    - ExportSong

  - name: Utilities
    children:
    - AppDelegate
    - Debouncer

  - name: Extensions
    children:
    - Image
    - View
    - NSWindow

# Command line for doc generation:
# jazzy
