title: Chord Provider
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/Chord-Provider/
build_tool_arguments:
 - -scheme
 - Chord Provider
# - -sdk
# - macosx
min_acl: private
output: Documentation
clean: true
theme: apple

source_host_files_url: https://github.com/desbeers/Chord-Provider/blob/main

skip_undocumented: true

modules:
  - module: Chord_Provider
  - module: SwiftlyChordUtilities

custom_categories:

  - name: SwiftUI
    children:
    - ChordProviderApp
    - WelcomeView
    - ContentView
    - MainView
    - ToolbarView
    - HeaderView
    - SongView
    - ChordsView
    - ChordDiagramView
    - AudioPlayerView
    - EditorView
    - FileBrowserView
    - ExportSongView
    - SettingsView
    - PrintSongView
    - ShareSongView
    - MarkupCommands

  - name: ChordPro
    children:
    - ChordPro
    - Song
    - Status

  - name: Observable Classes
    children:
    - AppState
    - SceneState
    - FileBrowser
    - ChordDisplayOptions
    - DocumentFocusedValueKey
    - SceneFocusedValueKey
    - FocusedValues

  - name: File Documents
    children:
    - ChordProDocument
    - ExportDocument
    - ExportSong

  - name: Utilities
    children:
    - AppDelegate
    - Debouncer

  - name: Extensions
    children:
    - Image
    - View
    - String
    - NSWindow

# Command line for doc generation:
# jazzy
