title: Chord Provider
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/Chord-Provider/
build_tool_arguments:
 - -scheme
 - Chord Provider
min_acl: private
output: Documentation
clean: true

copyright: © 2025 Nick Berendsen

source_host_files_url: https://github.com/desbeers/Chord-Provider/blob/main

exclude: /*/GeneratedAssetSymbols*
exclude: /*/Internal* 

theme: Resources/JazzyTheme

module: Chord_Provider

custom_categories:

  - name: General
    children:
    - ChordProviderApp
    - AppDelegate
    - AppSettings
    - AppError
    - AlertMessage
    - Help

  - name: Song structure
    children:
    - Song

  - name: Chord definitions
    children:
    - Chord
    - Chords
    - Instrument
    - Scales
    - Interval
    - ChordDefinition
    - Utils
    - Analizer
    - RegexDefinitions
    - Midi
    - MidiPlayer

  - name: ChordPro parser
    children:
    - ChordPro
    - ChordProParser

  - name: ChordPro editor
    children:
    - ChordProEditor
    - ChordProEditorDelegate
    - IntrospectCallback

  - name: PDF builder
    children:
    - SongExport
    - FolderExport
    - PDFBuild
    - PDFElement
    - PDFStringAttribute

  - name: SwiftUI Views
    children:
    - AboutView
    - WelcomeView
    - ColumnsLayout
    - MainView
    - ToolbarView
    - HeaderView
    - SongView
    - RenderView
    - ChordsView
    - ChordDiagramView
    - EditorView
    - PreviewPaneView
    - ExportFolderView
    - ChordDefinitionView
    - CreateChordView
    - ChordsDatabaseView
    - SettingsView
    - MediaPlayerView
    - HelpView
    - DebugView

  - name: SwiftUI Buttons
    children:
    - UserFileButton
    - ShareButton
    - PreviewPDFButton
    - PrintPDFButton
    - MetronomeButton
    - HelpButtons
    - FontSizeButtons
    - ExportSongButton
    - DebugButtons
    - ColorPickerButton

  - name: SwiftUI Other
    children:
    - Styles
    - Modifiers
    - AppKitUtils

  - name: Observable Classes
    children:
    - AppStateModel
    - SceneStateModel
    - FileBrowserModel
    - ImageViewModel
    - MetronomeModel
    - ChordsDatabaseStateModel

  - name: File Documents
    children:
    - ChordProDocument
    - ExportDocument
    - ChordsDatabaseDocument


# Command line for doc generation:
# jazzy
