title: Chord Provider
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/Chord-Provider/
build_tool_arguments:
 - -scheme
 - Chord Provider
# - -sdk
# - macosx
min_acl: private
output: Documentation
clean: true
theme: apple

copyright: © 2024 Nick Berendsen

hide_documentation_coverage: true

source_host_files_url: https://github.com/desbeers/Chord-Provider/blob/main

skip_undocumented: true

#exclude: /*/GeneratedAssetSymbols*,/*/resource_bundle_accessor*

#merge_modules: extensions

theme: JazzyTheme

modules:
  - module: Chord_Provider
  - module: SwiftlyChordUtilities

custom_categories:

  - name: General
    children:
    - ChordProviderApp
    - AppDelegate
    - ChordProviderSettings
    - ChordProviderGeneralOptions
    - ChordProviderError
    - Help

  - name: Song structure
    children:
    - Song

  - name: Chord definitions
    children:
    - Chord
    - Chords
    - Instrument
    - Scales
    - Interval
    - ChordDefinition
    - Utils
    - Analizer
    - RegexDefinitions
    - Database
    - Midi
    - MidiPlayer

  - name: ChordPro parser
    children:
    - ChordPro

  - name: ChordPro editor
    children:
    - ChordProEditor
    - ChordProEditorDelegate

  - name: PDF builder
    children:
    - SongExport
    - FolderExport
    - PDFBuild
    - PDFElement

  - name: SwiftUI
    children:
    - ColumnsLayout
    - TemplateView
    - ContentView
    - MainView
    - ToolbarView
    - HeaderView
    - SongView
    - ChordsView
    - ChordDiagramView
    - AudioPlayerView
    - MetronomeView
    - EditorView
    - FileBrowserView
    - SongFolderView
    - ExportSongView
    - ExportFolderView
    - SettingsView
    - PrintSongView
    - ChordDefinitionView
    - CreateChordView

  - name: Observable Classes
    children:
    - AppState
    - SceneState
    - FileBrowser
    - Metronome
    - DocumentFocusedValueKey
    - SceneFocusedValueKey
    - FocusedValues
    - ChordDisplayOptions

  - name: File Documents
    children:
    - ChordProDocument
    - ExportDocument


# Command line for doc generation:
# jazzy
