excluded:
  - ${PWD}/DerivedData

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - nesting
  - void_function_in_ternary

analyzer_rules:
  - unused_import

opt_in_rules:
  - array_init
#  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  #- redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  - yoda_condition


#custom_rules:
#  array_constructor:
#    name: "Array/Dictionary initializer"
#    regex: '[let,var] .+ = (\[.+\]\(\))'
#    capture_group: 1
#    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
#    severity: warning


#attributes:
#  always_on_same_line:
#    - "@main"
#    - "@objc"

force_cast: warning
force_try: warning

legacy_hashing: error

identifier_name:
  excluded:
    - x
    - y
    - up
    - id

indentation_width:
  indentation_width: 4
  include_compiler_directives: false

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  warning: 165

function_body_length:
  warning: 150

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

type_body_length:
    warning: 350

file_length:
    warning: 600

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12

large_tuple:
    warning: 4

function_parameter_count:
    warning: 7
